theme: jekyll-theme-minimal
title: "Ryan Kirkbride"
description: "
PhD student researching methods of collaboration in Live Coding music through software development and live performance. Python specialist and live improviser of melodic techno, deep house, and electro-pop using code."
logo: "presentation.png"
